### ISSUE TITLE
I'm having issues with multiple accounts.

### ISSUE THREAD

**Issue by viniciotricolor** [gamerbeaker007/splinterlands-stats#2]
"Hi friend, I'm having difficulty making it work in the current season. The main account works normally, but when it goes to the second one, it shows an error. I've already tried reversing the order of the secondary accounts, but the error persists."
using docker
docker run -it -v \tmp:/app/output -e "ACCOUNT_NAMES=viniciotricolor,rusbe,vinicio.spt,splinterlandspro" -e "SKIP_ZEROS=True" ghcr.io/gamerbeaker007/splinterlands-stats:latest

DEC: More then '13000' returned, continue for another balance pull...
DEC: all data pulled
VOUCHER: More then '1000' returned, continue for another balance pull...
VOUCHER: all data pulled
CREDITS: More then '1000' returned, continue for another balance pull...
CREDITS: all data pulled
SPS: More then '1000' returned, continue for another balance pull...
SPS: all data pulled
MERITS: More then '1000' returned, continue for another balance pull...
MERITS: all data pulled
SPS UNCLAIMED: More then '1000' returned, continue for another balance pull...
SPS UNCLAIMED: More then '2000' returned, continue for another balance pull...
SPS UNCLAIMED: More then '3000' returned, continue for another balance pull...
SPS: all data pulled
Get tournament and market info for season 108 Start: 2023-03-31 14:00:00+00:00 End: 2023-04-15 14:00:00+00:00
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3621, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 136, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 163, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 0

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 110, in <module>
    main()
  File "main.py", line 80, in main
    hive_blog.write_blog_post([account_name],
  File "/app/src/hive_blog.py", line 452, in write_blog_post
    post += get_tournament_results(tournaments_info_dict[account_name],
  File "/app/src/hive_blog.py", line 354, in get_tournament_results
    """ + str(get_tournament_info(tournaments_info)) + """ 
  File "/app/src/hive_blog.py", line 200, in get_tournament_info
    filters_sps_entry_fee.loc[:, 'fee_qty'] = split[0]
  File "/usr/local/lib/python3.8/site-packages/pandas/core/frame.py", line 3505, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/usr/local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3623, in get_loc
    raise KeyError(key) from err
KeyError: 0
![Captura de tela de 2023-04-16 20-44-10](https://user-images.githubusercontent.com/12204292/232349965-0fe2e882-f870-497c-b5a0-000241567004.png)

**Comment by gamerbeaker007** [comment]
Problem:  tournaments played by user and none of them payed out in  SPS. 
Added check if there are tournaments with SPS payout to determine SPS total earning of tournaments.
